import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { cache } from "react";
import ProductActions from "@/components/product-actions";
import { database,mapProduct } from "@/lib/database";
import { DEFAULT_CATALOG,money } from "@/lib/default-data";
import type { Product } from "@/lib/store-types";
export const dynamic="force-dynamic";
const getProduct=cache(async(slug:string):Promise<Product|null>=>{try{const row=await database().prepare("SELECT p.*,c.name AS category_name FROM products p JOIN categories c ON c.id=p.category_id WHERE p.slug=? AND p.active=1").bind(slug).first<Record<string,unknown>>();return row?mapProduct(row):null}catch{return DEFAULT_CATALOG.products.find(p=>p.slug===slug)||null}});
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params,p=await getProduct(slug);if(!p)return{title:"Produto não encontrado",robots:{index:false}};const image=p.imageUrl.startsWith("http")?p.imageUrl:`https://supermercado-central.joaopaulo2009.chatgpt.site${p.imageUrl}`;return{title:`${p.name} | Supermercado Central`,description:p.description,alternates:{canonical:`/produto/${p.slug}`},openGraph:{title:p.name,description:`${money(p.priceCents)} · ${p.unit}`,type:"website",images:[{url:image,alt:p.name}]},twitter:{card:"summary_large_image",title:p.name,description:`${money(p.priceCents)} no Supermercado Central`,images:[image]}}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params,p=await getProduct(slug);if(!p)return <main className="product-not-found"><h1>Produto não encontrado</h1><p>Ele pode estar temporariamente indisponível.</p><Link href="/#ofertas">Voltar ao catálogo</Link></main>;const related=DEFAULT_CATALOG.products.filter(x=>x.categoryId===p.categoryId&&x.id!==p.id).slice(0,4),schema={"@context":"https://schema.org","@type":"Product",name:p.name,image:[p.imageUrl],description:p.description,sku:p.sku,offers:{"@type":"Offer",priceCurrency:"BRL",price:(p.priceCents/100).toFixed(2),availability:p.stockQuantity>0?"https://schema.org/InStock":"https://schema.org/OutOfStock",url:`https://supermercado-central.joaopaulo2009.chatgpt.site/produto/${p.slug}`}};return <main className="product-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><header><Link href="/"><Image src="/assets/sc-supermercado-central-oficial.png" alt="Supermercado Central" width={220} height={90} unoptimized/></Link><Link href="/#ofertas">← Voltar ao catálogo</Link></header><nav className="breadcrumb"><Link href="/">Início</Link><span>›</span><Link href={`/#${p.categoryId}`}>{p.categoryName}</Link><span>›</span><b>{p.name}</b></nav><section className="product-detail"><div className="detail-image"><Image src={p.imageUrl} alt={p.name} fill sizes="(max-width:800px) 95vw,50vw" priority unoptimized/>{p.badge&&<span>{p.badge}</span>}</div><div className="detail-copy"><small>{p.categoryName} · {p.sku}</small><h1>{p.name}</h1><p>{p.description}</p><div className="detail-meta"><span>✓ Estoque disponível</span><span>✓ Qualidade selecionada</span><span>✓ Pedido pelo WhatsApp</span></div><div className="detail-price">{p.oldPriceCents&&<del>{money(p.oldPriceCents)}</del>}<strong>{money(p.priceCents)}</strong><small>{p.unit}</small></div><ProductActions product={p}/><div className="detail-info"><article><b>Entrega</b><p>Taxa e prazo calculados conforme a área selecionada no checkout.</p></article><article><b>Pagamento</b><p>PIX, dinheiro e cartões. Confirmação final pelo atendimento.</p></article></div></div></section>{related.length>0&&<section className="related"><span>VOCÊ TAMBÉM PODE GOSTAR</span><h2>Produtos relacionados</h2><div>{related.map(r=><Link key={r.id} href={`/produto/${r.slug}`}><Image src={r.imageUrl} alt={r.name} width={190} height={150} unoptimized/><b>{r.name}</b><small>{money(r.priceCents)}</small></Link>)}</div></section>}</main>}
