import type { CatalogPayload, Product } from "./store-types";
const slugify = (v: string) =>
  v
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
const product = (
  id: string,
  name: string,
  categoryId: string,
  categoryName: string,
  priceCents: number,
  unit: string,
  imageUrl: string,
  extras: Partial<Product> = {},
): Product => ({
  id,
  sku: `SC-${id.padStart(4, "0")}`,
  barcode: "",
  brand: "",
  name,
  slug: slugify(name),
  description: `${name} selecionado com qualidade pelo Supermercado Central.`,
  categoryId,
  categoryName,
  priceCents,
  oldPriceCents: null,
  costCents: 0,
  unit,
  saleMode: "unit",
  quantityStep: 1,
  minimumQuantity: 1,
  options: [],
  imageUrl,
  badge: "",
  stockQuantity: 50,
  minStock: 5,
  active: true,
  featured: false,
  offerStart: null,
  offerEnd: null,
  ...extras,
});
export const DEFAULT_CATALOG: CatalogPayload = {
  categories: [
    {
      id: "mercearia",
      name: "Mercearia",
      slug: "mercearia",
      icon: "🛒",
      sortOrder: 1,
      active: true,
    },
    {
      id: "hortifruti",
      name: "Hortifruti",
      slug: "hortifruti",
      icon: "🥬",
      sortOrder: 2,
      active: true,
    },
    {
      id: "acougue",
      name: "Açougue",
      slug: "acougue",
      icon: "🥩",
      sortOrder: 3,
      active: true,
    },
    {
      id: "padaria",
      name: "Padaria",
      slug: "padaria",
      icon: "🥖",
      sortOrder: 4,
      active: true,
    },
    {
      id: "bebidas",
      name: "Bebidas",
      slug: "bebidas",
      icon: "🥤",
      sortOrder: 5,
      active: true,
    },
    {
      id: "laticinios",
      name: "Laticínios",
      slug: "laticinios",
      icon: "🧀",
      sortOrder: 6,
      active: true,
    },
    {
      id: "limpeza",
      name: "Casa & Limpeza",
      slug: "limpeza",
      icon: "🧼",
      sortOrder: 7,
      active: true,
    },
  ],
  products: [
    product(
      "1",
      "Arroz Branco Tipo 1",
      "mercearia",
      "Mercearia",
      2499,
      "Pacote 5kg",
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=700&q=85",
      { oldPriceCents: 2990, badge: "Oferta", featured: true },
    ),
    product(
      "2",
      "Feijão Carioca",
      "mercearia",
      "Mercearia",
      799,
      "Pacote 1kg",
      "https://images.unsplash.com/photo-1551462147-ff29053bfc14?auto=format&fit=crop&w=700&q=85",
      { oldPriceCents: 949, badge: "-16%" },
    ),
    product(
      "3",
      "Leite Integral",
      "laticinios",
      "Laticínios",
      549,
      "Caixa 1L",
      "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=700&q=85",
      {
        brand: "Central",
        options: [
          {
            id: "1l",
            label: "Caixa 1L",
            priceCents: 549,
            oldPriceCents: null,
            barcode: "",
          },
          {
            id: "fardo-12",
            label: "Fardo com 12 unidades",
            priceCents: 6290,
            oldPriceCents: 6590,
            barcode: "",
          },
        ],
      },
    ),
    product(
      "4",
      "Café Torrado e Moído",
      "mercearia",
      "Mercearia",
      1690,
      "Pacote 500g",
      "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=700&q=85",
      { oldPriceCents: 1990, badge: "Oferta", featured: true },
    ),
    product(
      "5",
      "Banana Prata",
      "hortifruti",
      "Hortifruti",
      579,
      "1kg aprox.",
      "https://images.unsplash.com/photo-1603833665858-e61d17a86224?auto=format&fit=crop&w=700&q=85",
      { saleMode: "weight", quantityStep: 0.25, minimumQuantity: 0.5 },
    ),
    product(
      "6",
      "Tomate Selecionado",
      "hortifruti",
      "Hortifruti",
      749,
      "1kg aprox.",
      "https://images.unsplash.com/photo-1561136594-7f68413baa99?auto=format&fit=crop&w=700&q=85",
      {
        oldPriceCents: 899,
        badge: "Fresquinho",
        saleMode: "weight",
        quantityStep: 0.25,
        minimumQuantity: 0.5,
      },
    ),
    product(
      "7",
      "Refrigerante Cola",
      "bebidas",
      "Bebidas",
      999,
      "Garrafa 2L",
      "https://images.unsplash.com/photo-1581006852262-e4307cf6283a?auto=format&fit=crop&w=700&q=85",
      {
        options: [
          {
            id: "2l",
            label: "Garrafa 2L",
            priceCents: 999,
            oldPriceCents: null,
            barcode: "",
          },
          {
            id: "fardo-6",
            label: "Fardo com 6 garrafas",
            priceCents: 5690,
            oldPriceCents: 5990,
            barcode: "",
          },
        ],
      },
    ),
    product(
      "8",
      "Carne Bovina para Bife",
      "acougue",
      "Açougue",
      3490,
      "1kg aprox.",
      "https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=700&q=85",
      {
        oldPriceCents: 3990,
        badge: "Oferta",
        featured: true,
        saleMode: "weight",
        quantityStep: 0.25,
        minimumQuantity: 0.5,
      },
    ),
    product(
      "9",
      "Pão Francês Fresquinho",
      "padaria",
      "Padaria",
      1490,
      "1kg aprox.",
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=700&q=85",
      { saleMode: "weight", quantityStep: 0.25, minimumQuantity: 0.25 },
    ),
    product(
      "10",
      "Queijo Muçarela",
      "laticinios",
      "Laticínios",
      4290,
      "1kg aprox.",
      "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=700&q=85",
      { saleMode: "weight", quantityStep: 0.25, minimumQuantity: 0.25 },
    ),
  ],
  settings: {
    storeName: "Supermercado Central",
    whatsapp: "5582982016966",
    phone: "(82) 98201-6966",
    address:
      "Avenida Deputado Elisio da Silva Maia, 19 - Centro, São José da Tapera - AL",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=Avenida+Deputado+Elisio+da+Silva+Maia%2C+19+-+Centro%2C+S%C3%A3o+Jos%C3%A9+da+Tapera+-+Alagoas",
    hours: "7h30 às 21h",
    paymentMethods: "PIX, Dinheiro, Cartão",
    pixKey: "",
    pixMerchantName: "SUPERMERCADO CENTRAL",
    pixMerchantCity: "MACEIO",
    minimumOrderCents: 3000,
    allowPickup: true,
    allowDelivery: true,
    substitutionPolicy: "confirm",
    announcement: "Ofertas especiais todos os dias",
    loyaltyEnabled: true,
    pointsPerReal: 1,
    reviewEnabled: true,
    flashOfferTitle: "Oferta-relâmpago",
    abandonedCartHours: 24,
  },
  deliveryZones: [
    {
      id: "centro",
      name: "Centro",
      feeCents: 500,
      minimumOrderCents: 3000,
      freeShippingCents: 15000,
      eta: "35–55 min",
      active: true,
    },
    {
      id: "outros",
      name: "Outros bairros",
      feeCents: 800,
      minimumOrderCents: 5000,
      freeShippingCents: 20000,
      eta: "50–80 min",
      active: true,
    },
  ],
  banners: [
    {
      id: "oferta-semana",
      title: "Até 30% OFF",
      subtitle: "Ofertas selecionadas desta semana",
      imageUrl: "",
      ctaLabel: "Aproveitar",
      ctaUrl: "#ofertas",
      active: true,
      sortOrder: 1,
    },
  ],
  homeContent: {
    aboutEyebrow: "PERTINHO DE VOCÊ",
    aboutTitle: "Qualidade e atendimento que fazem parte da sua rotina.",
    aboutText:
      "Uma experiência de compra pensada para as famílias de São José da Tapera, com variedade, cuidado e atendimento próximo.",
    storefrontImageUrl: "",
    interiorImageUrl: "",
    teamImageUrl: "",
    flyerEyebrow: "ENCARTE DA SEMANA",
    flyerTitle: "Economia para encher o carrinho.",
    flyerSubtitle:
      "Uma seleção atualizada de ofertas para você aproveitar pelo site ou na loja.",
    flyerImageUrl: "",
    flyerCtaLabel: "Ver todas as ofertas",
    flyerCtaUrl: "#ofertas",
    flyerStartsAt: null,
    flyerEndsAt: null,
    flyerActive: true,
  },
};
export const money = (cents: number) =>
  new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(
    cents / 100,
  );
