export type Product = {
  id: string;
  sku: string;
  barcode: string;
  brand: string;
  name: string;
  slug: string;
  description: string;
  categoryId: string;
  categoryName: string;
  priceCents: number;
  oldPriceCents: number | null;
  costCents: number;
  unit: string;
  saleMode: "unit" | "weight";
  quantityStep: number;
  minimumQuantity: number;
  options: ProductOption[];
  imageUrl: string;
  badge: string;
  stockQuantity: number;
  minStock: number;
  active: boolean;
  featured: boolean;
  offerStart: string | null;
  offerEnd: string | null;
};
export type ProductOption = {
  id: string;
  label: string;
  priceCents: number;
  oldPriceCents: number | null;
  barcode: string;
};
export type Category = {
  id: string;
  name: string;
  slug: string;
  icon: string;
  sortOrder: number;
  active: boolean;
};
export type StoreSettings = {
  storeName: string;
  whatsapp: string;
  phone: string;
  address: string;
  mapsUrl: string;
  hours: string;
  paymentMethods: string;
  pixKey: string;
  pixMerchantName: string;
  pixMerchantCity: string;
  minimumOrderCents: number;
  allowPickup: boolean;
  allowDelivery: boolean;
  substitutionPolicy: string;
  announcement: string;
  loyaltyEnabled: boolean;
  pointsPerReal: number;
  reviewEnabled: boolean;
  flashOfferTitle: string;
  abandonedCartHours: number;
};
export type DeliveryZone = {
  id: string;
  name: string;
  feeCents: number;
  minimumOrderCents: number;
  freeShippingCents: number;
  eta: string;
  active: boolean;
};
export type Coupon = {
  code: string;
  type: "percent" | "fixed" | "free_shipping";
  value: number;
  maxDiscountCents: number | null;
  minimumCents: number;
  startsAt: string | null;
  endsAt: string | null;
  usageLimit: number;
  usedCount: number;
  active: boolean;
};
export type Banner = {
  id: string;
  title: string;
  subtitle: string;
  imageUrl: string;
  ctaLabel: string;
  ctaUrl: string;
  active: boolean;
  sortOrder: number;
};
export type HomeContent = {
  aboutEyebrow: string;
  aboutTitle: string;
  aboutText: string;
  storefrontImageUrl: string;
  interiorImageUrl: string;
  teamImageUrl: string;
  flyerEyebrow: string;
  flyerTitle: string;
  flyerSubtitle: string;
  flyerImageUrl: string;
  flyerCtaLabel: string;
  flyerCtaUrl: string;
  flyerStartsAt: string | null;
  flyerEndsAt: string | null;
  flyerActive: boolean;
};
export type CatalogPayload = {
  products: Product[];
  categories: Category[];
  settings: StoreSettings;
  deliveryZones: DeliveryZone[];
  banners: Banner[];
  homeContent: HomeContent;
};
export type Cart = Record<string, number>;
export type CartOptions = Record<string, string>;
export type ItemSubstitution = "confirm" | "similar" | "none";
export type ItemSubstitutions = Record<string, ItemSubstitution>;
export type ShoppingList = {
  id: string;
  name: string;
  cart: Cart;
  options: CartOptions;
  substitutions: ItemSubstitutions;
  updatedAt: string;
};
export type StoreNotification = {
  id: string;
  title: string;
  body: string;
  url: string;
  active: boolean;
  publishedAt: string | null;
  expiresAt: string | null;
};
export type CheckoutCustomer = {
  name: string;
  phone: string;
  deliveryType: "delivery" | "pickup";
  postalCode: string;
  city: string;
  state: string;
  address: string;
  neighborhood: string;
  reference: string;
  paymentMethod: string;
  changeFor: string;
  scheduledFor: string;
  notes: string;
  substitution: string;
  couponCode: string;
  referralCode: string;
};
export type OrderHistoryEntry = {
  orderNumber: string;
  trackingToken: string;
  createdAt: string;
  totalCents: number;
  status?: string;
  cart: Cart;
  options?: CartOptions;
  substitutions?: ItemSubstitutions;
};
export type PublicReview = {
  id: number;
  customerName: string;
  rating: number;
  comment: string;
  createdAt: string;
};
